config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_all'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def trash_em
		@trash_em = List.where(:completed => true).destroy_all
		redirect_to lists_url, notice: 'All marked tasks were successfully deleted.'
	end

	def trash_all
		@trash_all = List.all.destroy_all
		redirect_to lists_url, notice: 'All tasks were successfully deleted.'
	end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'lists/navbar' %>
    <div class="container">
      <br/>
      <%= render 'flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-success alert-dismissible">
		<button class="close" data-dismiss="alert">
			<small><sup>x</sup></small>
		</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: "form-check-input" %>
    <%= form.label :completed, class: "form-check-label" %>
  </div>

  <div class="actions">
    <%= form.submit "Update Task", class: "btn" %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this @list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="form-inline my-2 my-lg-0">
      <div class="form-group">
        <%= form.label :description, class: "sr-only" %>
        <%= form.text_field :description, placeholder: "Description", class: "form-control mr-sm-2" %>
      </div>
      <div class=" form-group">
        <%= form.submit "Add task", class: "btn btn-primary my-2 my-sm-0" %>
      </div>
    </div>
  </div>

<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<%= link_to "Todo List", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<i class="fas fa-plus"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
			</ul>
			<%= render 'form_index' %>
		</div>
	</div>
</nav>

app/views/lists/edit.html.erb
<h1>Edit Task</h1>
<br/>
<div class="card" style="width:18rem">
	<div class="card-body">
		<%= render 'form', list: @list %>
	</div>
</div>

<br/><br/>

<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<div class="container">
  <table class="table">

    <tbody>
      <% @lists.each do |list| %>
        <% if list.completed %>
        <tr class="completed">
          <td>
            <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: "hidden" %>
              <%= f.check_box :completed, :checked => false, :style => "visibility:hidden" %>
              <%= button_tag( :class => "btn btn-sm btn-secondary") do %>
                <i class="fas fa-check"></i>
              <% end %>
            <% end %>
          </td>
          <td class="desc"><%= link_to list.description, edit_list_path(list) %></td>          
          <td style="text-align: right;">   
            <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, list, method: :delete, class: 'btn btn-outline-danger btn-sm', data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% else %>
        <tr>
          <td>
            <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: "hidden" %>
              <%= f.check_box :completed, :checked => true, :style => "visibility:hidden" %>
              <%= button_tag( :class => "btn btn-sm btn-secondary") do %>
                <i class="fas fa-square" style="opacity:0"></i>
              <% end %>
            <% end %>
          </td>
          <td class="desc"><%= link_to list.description, edit_list_path(list) %></td>          
          <td style="text-align: right;">   
            <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, list, method: :delete, class: 'btn btn-outline-danger btn-sm', data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br/><br/>
  <nav class="navbar fixed-bottom navbar-light bg-light d-flex justify-content-center">
    <%= link_to 'Delete Marked Tasks', home_trash_em_path, class: 'btn btn-secondary btn-sm mr-1', data: { confirm: 'Are you sure?' }%>
    <%= link_to 'Delete All Tasks', home_trash_all_path, class: 'btn btn-outline-secondary btn-sm ml-1', data: { confirm: 'Are you sure?' }%>
  </nav>
  
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>